### ISSUE TITLE
Secrets exposed in repo

### ISSUE THREAD

**Issue by dragid10** [suraj-ranganath/bookpal#1]
Hey there, I accidentally stumbled upon this repo while I was looking for a book API. 

I saw that you had committed your Goodreads api keys previously and have changed them in a recent commit. Unfortunately those keys are still searchable in your git history. 

I'd recommend using BFG to purge those secrets from your commit history, as well as regenerating your credentials
https://rtyley.github.io/bfg-repo-cleaner/

**Comment by suraj-ranganath** [comment]
Took a while, but it's done now. Thank You @dragid10 !
